### ISSUE TITLE
kubeflow create ks-secret

### ISSUE THREAD

**Issue by snowch** [hpe-container-platform-community/hcp-demo-env-aws-terraform#24]
```
GET /api/v2/k8skubeconfig/ HTTP/1.1
Host: 127.0.0.1:8080
Accept-Encoding: gzip, deflate
REMOTE_ADDR: 86.191.225.157
Accept: */*
User-Agent: python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-1160.21.1.el7.x86_64
Connection: keep-alive
X-BDS-SESSION: /api/v2/session/7ffd642a-a530-4c65-9f27-564ff0b0a5d0
Authorization: /api/v2/session/7ffd642a-a530-4c65-9f27-564ff0b0a5d0

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Disposition: attachment; filename="config"
Content-Length: 2507
Content-Type: text/yaml
Date: Sat, 20 Mar 2021 06:14:18 GMT
Server: HPE Ezmeral Container Platform 5.3

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lKQU50SW5tTDVvMzVKTUEwR0NTcUdTSWIzRFFFQkN3VUFNREV4THpBdEJnTlYKQkFNTUptbHdMVEV3TFRFdE1DMDVMbVYxTFhkbGMzUXRNeTVqYjIxd2RYUmxMbWx1ZEdWeWJtRnNNQjRYRFRJeApNRE14T1RJeU5ERTBNRm9YRFRJek1ETXhPVEl5TkRFME1Gb3dNVEV2TUMwR0ExVUVBd3dtYVhBdE1UQXRNUzB3CkxUa3VaWFV0ZDJWemRDMHpMbU52YlhCMWRHVXVhVzUwWlhKdVlXd3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUEKQTRJQkR3QXdnZ0VLQW9JQkFRRHc1QnZ6NjEwcU5vdWI4Qnh6YW04N2hsd2lIdW0vRm9LaExmYTF2cmNaQm1aZgp4UTlRY3orSkpUaUVtRnJkS0pEZDlBaWx5VVlxMDVWVjk5ckM3OTdWSFRQRHdQeXhlQ2R3M3BMajFreTJEbGVZCmV2emRIU2ptY2lNWVlIMFhkR3E0ZURXWnNqU2lVMXF5Q01LY0lxTVlScGhOR2hDVnc2bDJvVXBkaGVwcUhXZUYKR0xTckNFc0gvTUhtbVdyNGsySmE2SnNxZ1FzZFZCQUVYVUV0enJPd1Evd1pRRDhUS1FXa2w5a3FHQnNHYVNvSwo1SytDbzUrTUVGY2w0emw4anlndjdWK0d1NDdPN0RPWDJRR05HWHBERVdrVS83YzdQUXhqalV5RlduTld4aEV2Cnp0QjVhc0Fnd0tkMDhlR1UzaTk0Z2ZzR1FwSHFRYVYzcHdJQzQyYVRBZ01CQUFHalVEQk9NQjBHQTFVZERnUVcKQkJRMlhDWi9lQkR4bzMwa0RERXhXR28zMk9GVTd6QWZCZ05WSFNNRUdEQVdnQlEyWENaL2VCRHhvMzBrRERFeApXR28zMk9GVTd6QU1CZ05WSFJNRUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFDZ3AyNC8yN2ZlCjgveEJ2RFVMOGVKYjZFUXlXcXVXckp3bC9Mc2d1TXR5THBIYklJUFE1d096bXBtYVR5bnJocTBXWE5kWG9mdjkKeGxRL25LRjA2My96bVJWSE16VDFVK2JTUmpnOXZHeGtIMFA2aWswTFRzTFREdkZmL0NRWitGZGU2VHN3clN0WAp3M3BnenVoajVnd1lrWDAwZlRLNjk0SE81TCtkOVlYUjZnV29ZSkg0eXora3Zwdy9iNFJHaUwzdzFPZHVBd0FPCjMyNGFvbkJYcy8yNHBsQ1Z4azJLU0xwZWJzaHo0QVBaeERpWHFNWGVKT0prTTlnTytDVEt0N0ZUSy9sWC80TisKRnN3TE9jZTZPSEJJcjJBVlpXWVZNTTJSRU5HeTNHMnRxNk00MGhLejJ1VjVJeFYxU1Z3ZE9LZjd5RytxMDhmMwprVGZoSUcvUjIyK3oKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://ip-10-1-0-23.eu-west-3.compute.internal:9500
  name: demo-hpecp-c1
contexts:
- context:
    cluster: demo-hpecp-c1
    user: demo-hpecp-admin
  name: demo-hpecp-c1-admin
- context:
    cluster: demo-hpecp-c1
    user: demo-hpecp-admin
    namespace: hpecp-tenant-4-8rbcx
  name: demo-hpecp-c1-k8s-tenant-1-admin
current-context: demo-hpecp-c1-k8s-tenant-1-admin
kind: Config
preferences: {}
users:
- name: demo-hpecp-admin
  user:
    exec:
      command: kubectl
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - hpecp
      - authenticate
      - ip-10-1-0-23.eu-west-3.compute.internal:8080
      - --hpecp-user=admin
      - --hpecp-token=/api/v2/session/7ffd642a-a530-4c65-9f27-564ff0b0a5d0
      - --hpecp-token-expiry=1616307228
      - --force-reauth=false
      - --insecure=true
      - --insecure-skip-tls-verify=true
```

```
POST /api/v2/k8scluster/1/kubectl HTTP/1.1
Host: 127.0.0.1:8080
Content-Length: 3844
Accept-Encoding: gzip, deflate
REMOTE_ADDR: 86.191.225.157
Accept: */*
User-Agent: python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-1160.21.1.el7.x86_64
Connection: keep-alive
X-BDS-SESSION: /api/v2/session/7ffd642a-a530-4c65-9f27-564ff0b0a5d0
Authorization: /api/v2/session/7ffd642a-a530-4c65-9f27-564ff0b0a5d0

{"data": "eyJzdHJpbmdEYXRhIjogeyJjb25maWciOiAiYXBpVmVyc2lvbjogdjFcbmNsdXN0ZXJzOlxuLSBjbHVzdGVyOlxuICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VST1ZFTkRRV2d5WjBGM1NVSkJaMGxLUVU1MFNXNXRURFZ2TXpWS1RVRXdSME5UY1VkVFNXSXpSRkZGUWtOM1ZVRk5SRVY0VEhwQmRFSm5UbFlLUWtGTlRVcHRiSGRNVkVWM1RGUkZkRTFETURWTWJWWXhURmhrYkdNelVYUk5lVFZxWWpJeGQyUllVbXhNYld4MVpFZFdlV0p0Um5OTlFqUllSRlJKZUFwTlJFMTRUMVJKZVU1RVJUQk5SbTlZUkZSSmVrMUVUWGhQVkVsNVRrUkZNRTFHYjNkTlZFVjJUVU13UjBFeFZVVkJkM2R0WVZoQmRFMVVRWFJOVXpCM0NreFVhM1ZhV0ZWMFpESldlbVJETUhwTWJVNTJZbGhDTVdSSFZYVmhWelV3V2xoS2RWbFhkM2RuWjBWcFRVRXdSME5UY1VkVFNXSXpSRkZGUWtGUlZVRUtRVFJKUWtSM1FYZG5aMFZMUVc5SlFrRlJSSGMxUW5aNk5qRXdjVTV2ZFdJNFFuaDZZVzA0TjJoc2QybElkVzB2Um05TGFFeG1ZVEYyY21OYVFtMWFaZ3A0VVRsUlkzb3JTa3BVYVVWdFJuSmtTMHBFWkRsQmFXeDVWVmx4TURWV1ZqazVja00zT1RkV1NGUlFSSGRRZVhobFEyUjNNM0JNYWpGcmVUSkViR1ZaQ21WMmVtUklVMnB0WTJsTldWbElNRmhrUjNFMFpVUlhXbk5xVTJsVk1YRjVRMDFMWTBseFRWbFNjR2hPUjJoRFZuYzJiREp2VlhCa2FHVndjVWhYWlVZS1IweFRja05GYzBndlRVaHRiVmR5TkdzeVNtRTJTbk54WjFGelpGWkNRVVZZVlVWMGVuSlBkMUV2ZDFwUlJEaFVTMUZYYTJ3NWEzRkhRbk5IWVZOdlN3bzFTeXREYnpVclRVVkdZMncwZW13NGFubG5kamRXSzBkMU5EZFBOMFJQV0RKUlIwNUhXSEJFUlZkclZTODNZemRRVVhocWFsVjVSbGR1VGxkNGFFVjJDbnAwUWpWaGMwRm5kMHRrTURobFIxVXphVGswWjJaelIxRndTSEZSWVZZemNIZEpRelF5WVZSQlowMUNRVUZIYWxWRVFrOU5RakJIUVRGVlpFUm5VVmNLUWtKUk1saERXaTlsUWtSNGJ6TXdhMFJFUlhoWFIyOHpNazlHVlRkNlFXWkNaMDVXU0ZOTlJVZEVRVmRuUWxFeVdFTmFMMlZDUkhodk16QnJSRVJGZUFwWFIyOHpNazlHVlRkNlFVMUNaMDVXU0ZKTlJVSlVRVVJCVVVndlRVRXdSME5UY1VkVFNXSXpSRkZGUWtOM1ZVRkJORWxDUVZGRFozQXlOQzh5TjJabENqZ3ZlRUoyUkZWTU9HVktZalpGVVhsWGNYVlhja3AzYkM5TWMyZDFUWFI1VEhCSVlrbEpVRkUxZDA5NmJYQnRZVlI1Ym5Kb2NUQlhXRTVrV0c5bWRqa0tlR3hSTDI1TFJqQTJNeTk2YlZKV1NFMTZWREZWSzJKVFVtcG5PWFpIZUd0SU1GQTJhV3N3VEZSelRGUkVka1ptTDBOUldpdEdaR1UyVkhOM2NsTjBXQXAzTTNCbmVuVm9halZuZDFscldEQXdabFJMTmprMFNFODFUQ3RrT1ZsWVVqWm5WMjlaU2tnMGVYb3JhM1p3ZHk5aU5GSkhhVXd6ZHpGUFpIVkJkMEZQQ2pNeU5HRnZia0pZY3k4eU5IQnNRMVo0YXpKTFUweHdaV0p6YUhvMFFWQmFlRVJwV0hGTldHVktUMHByVFRsblR5dERWRXQwTjBaVVN5OXNXQzgwVGlzS1JuTjNURTlqWlRaUFNFSkpjakpCVmxwWFdWWk5UVEpTUlU1SGVUTkhNblJ4TmswME1HaExlakoxVmpWSmVGWXhVMVozWkU5TFpqZDVSeXR4TURobU13cHJWR1pvU1VjdlVqSXlLM29LTFMwdExTMUZUa1FnUTBWU1ZFbEdTVU5CVkVVdExTMHRMUW89XG4gICAgc2VydmVyOiBodHRwczovL2lwLTEwLTEtMC0yMy5ldS13ZXN0LTMuY29tcHV0ZS5pbnRlcm5hbDo5NTAwXG4gIG5hbWU6IGRlbW8taHBlY3AtYzFcbmNvbnRleHRzOlxuLSBjb250ZXh0OlxuICAgIGNsdXN0ZXI6IGRlbW8taHBlY3AtYzFcbiAgICB1c2VyOiBkZW1vLWhwZWNwLWFkbWluXG4gIG5hbWU6IGRlbW8taHBlY3AtYzEtYWRtaW5cbi0gY29udGV4dDpcbiAgICBjbHVzdGVyOiBkZW1vLWhwZWNwLWMxXG4gICAgdXNlcjogZGVtby1ocGVjcC1hZG1pblxuICAgIG5hbWVzcGFjZTogaHBlY3AtdGVuYW50LTQtOHJiY3hcbiAgbmFtZTogZGVtby1ocGVjcC1jMS1rOHMtdGVuYW50LTEtYWRtaW5cbmN1cnJlbnQtY29udGV4dDogZGVtby1ocGVjcC1jMS1rOHMtdGVuYW50LTEtYWRtaW5cbmtpbmQ6IENvbmZpZ1xucHJlZmVyZW5jZXM6IHt9XG51c2Vyczpcbi0gbmFtZTogZGVtby1ocGVjcC1hZG1pblxuICB1c2VyOlxuICAgIGV4ZWM6XG4gICAgICBjb21tYW5kOiBrdWJlY3RsXG4gICAgICBhcGlWZXJzaW9uOiBjbGllbnQuYXV0aGVudGljYXRpb24uazhzLmlvL3YxYmV0YTFcbiAgICAgIGFyZ3M6XG4gICAgICAtIGhwZWNwXG4gICAgICAtIGF1dGhlbnRpY2F0ZVxuICAgICAgLSBpcC0xMC0xLTAtMjMuZXUtd2VzdC0zLmNvbXB1dGUuaW50ZXJuYWw6ODA4MFxuICAgICAgLSAtLWhwZWNwLXVzZXI9YWRtaW5cbiAgICAgIC0gLS1ocGVjcC10b2tlbj0vYXBpL3YyL3Nlc3Npb24vN2ZmZDY0MmEtYTUzMC00YzY1LTlmMjctNTY0ZmYwYjBhNWQwXG4gICAgICAtIC0taHBlY3AtdG9rZW4tZXhwaXJ5PTE2MTYzMDcyMjhcbiAgICAgIC0gLS1mb3JjZS1yZWF1dGg9ZmFsc2VcbiAgICAgIC0gLS1pbnNlY3VyZT10cnVlXG4gICAgICAtIC0taW5zZWN1cmUtc2tpcC10bHMtdmVyaWZ5PXRydWVcbiJ9LCAia2luZCI6ICJTZWNyZXQiLCAiYXBpVmVyc2lvbiI6ICJ2MSIsICJtZXRhZGF0YSI6IHsibGFiZWxzIjogeyJrdWJlZGlyZWN0b3IuaHBlLmNvbS91c2VybmFtZSI6ICJhZG1pbiIsICJrdWJlZGlyZWN0b3IuaHBlLmNvbS91c2VyaWQiOiAiNiIsICJrdWJlZGlyZWN0b3IuaHBlLmNvbS9zZWNyZXRUeXBlIjogImt1YmVjb25maWcifSwgIm5hbWVzcGFjZSI6ICJocGVjcC10ZW5hbnQtNC04cmJjeCIsICJuYW1lIjogImhwZWNwLWtjLXNlY3JldC0xNmRjZmQ2NTNlYWRiM2VkMDNjMWExNzMyOTQzMTU4YyJ9fQ==", "op": "create"}HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Length: 63
Content-Type: text/plain
Date: Sat, 20 Mar 2021 06:14:19 GMT
Server: HPE Ezmeral Container Platform 5.3

secret/hpecp-kc-secret-16dcfd653eadb3ed03c1a1732943158c created
```

base64 decoded

```
{
  "stringData": {
    "config": "apiVersion: v1\nclusters:\n- cluster:\n    certificate-authority-data: XXXXXXXXX=\n    server: https://ip-10-1-0-23.eu-west-3.compute.internal:9500\n  name: demo-hpecp-c1\ncontexts:\n- context:\n    cluster: demo-hpecp-c1\n    user: demo-hpecp-admin\n  name: demo-hpecp-c1-admin\n- context:\n    cluster: demo-hpecp-c1\n    user: demo-hpecp-admin\n    namespace: hpecp-tenant-4-8rbcx\n  name: demo-hpecp-c1-k8s-tenant-1-admin\ncurrent-context: demo-hpecp-c1-k8s-tenant-1-admin\nkind: Config\npreferences: {}\nusers:\n- name: demo-hpecp-admin\n  user:\n    exec:\n      command: kubectl\n      apiVersion: client.authentication.k8s.io/v1beta1\n      args:\n      - hpecp\n      - authenticate\n      - ip-10-1-0-23.eu-west-3.compute.internal:8080\n      - --hpecp-user=admin\n      - --hpecp-token=/api/v2/session/7ffd642a-a530-4c65-9f27-564ff0b0a5d0\n      - --hpecp-token-expiry=1616307228\n      - --force-reauth=false\n      - --insecure=true\n      - --insecure-skip-tls-verify=true\n"
  },
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "labels": {
      "kubedirector.hpe.com/username": "admin",
      "kubedirector.hpe.com/userid": "6",
      "kubedirector.hpe.com/secretType": "kubeconfig"
    },
    "namespace": "hpecp-tenant-4-8rbcx",
    "name": "hpecp-kc-secret-16dcfd653eadb3ed03c1a1732943158c"
  }
}
```
